# Generated by Django 2.1.5 on 2019-03-02 19:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nif', models.IntegerField()),
                ('n_cc', models.IntegerField()),
                ('dob', models.DateField()),
                ('institucional_email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('emergency_contact', models.IntegerField()),
                ('professional_occupation', models.TextField(max_length=512)),
                ('display_image', models.ImageField(upload_to='')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=8)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('appuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AppUser')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.appuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('appuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AppUser')),
                ('number', models.IntegerField()),
                ('rank', models.CharField(choices=[('assist', 'Assistant Professor'), ('assistinv', 'Invited Assistant Professor'), ('full', 'Full Professor'), ('fullvis', 'Visiting Full Professor'), ('associ', 'Associate Professor'), ('associnv', 'Invited Associate Professor'), ('assocagr', 'Associate Professor with Agregação')], max_length=9)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.appuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('appuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AppUser')),
                ('number', models.IntegerField()),
                ('call', models.CharField(choices=[('1', '1st Call'), ('2', '2nd Call')], max_length=1)),
                ('entry_grade', models.FloatField(max_length=200.0)),
                ('statute', models.CharField(choices=[('worker', 'Worker'), ('athlete', 'Athlete'), ('fireman', 'Fireman'), ('military', 'Military'), ('union', "Student's Union"), ('special', 'Special Learning Needs'), ('parent', 'Parent')], max_length=8)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.appuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
