# Generated by Django 2.1.7 on 2019-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='display_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='professional_occupation',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
