# Generated by Django 2.1.7 on 2019-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
