# Generated by Django 2.1.7 on 2019-03-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190316_1512'),
        ('users', '0003_auto_20190316_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
