# Generated by Django 2.1.7 on 2019-03-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190304_2252'),
        ('users', '0003_auto_20190305_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.Faculty'),
            preserve_default=False,
        ),
    ]
