# Generated by Django 2.1.7 on 2019-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='n_cc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='nif',
            field=models.PositiveIntegerField(),
        ),
    ]
