# Generated by Django 2.1.7 on 2019-03-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190306_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'administrator', 'verbose_name_plural': 'administrators'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'professor', 'verbose_name_plural': 'professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
