# Generated by Django 2.1.7 on 2019-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190323_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='display_image',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
    ]
