version: "3.6"
services:
  nginx:
    image: zelda-nginx:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certbot/etc/letsencrypt:/etc/letsencrypt:rw
      - ~/certbot/var/www/certbot:/var/www/certbot:rw
      - ~/nginx/conf.d:/etc/nginx/conf.d:ro
      - ~/nginx/logs/zelda:/zelda/logs:rw
      - ~/zelda/static:/zelda/static:ro
  zelda:
    image: zelda:latest
    networks:
      zelda: {}
    deploy:
      replicas: ${DJANGO_REPLICAS}
      restart_policy:
        condition: always
    depends_on:
      - cache
    volumes:
      - ~/zelda/data:/zelda/data:rw
      - ~/zelda/logs:/zelda/logs:rw
      - ~/zelda/static:/zelda/static:rw
  cache:
    image: memcached:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: always
      placements:
        constraints: [node.role == manager]
  certbot:
    image: zelda-certbot:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/certbot/etc/letsencrypt:/etc/letsencrypt:rw
      - ~/certbot/var/www/certbot:/var/www/certbot:rw
networks:
  zelda: {}
