FROM python:3.6

WORKDIR /zelda

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

RUN rm requirements.txt

VOLUME [ "/zelda/code" ]

ENV PROJECT_DIR=/zelda/code

ENTRYPOINT [ "code/scripts/start-dev.sh" ]
