FROM nginx:latest

COPY init-nginx-mgmt.sh init-nginx.sh

COPY config/ /etc/nginx/

COPY conf.d/cert-mgmt.conf /etc/nginx/conf.d/cert-mgmt.conf

RUN rm /etc/nginx/conf.d/default.conf

VOLUME [ \
    "/mgmt/logs", \
    "/var/www/certbot" \
]

CMD [ "./init-nginx.sh" ]
