# Generated by Django 2.1.7 on 2019-03-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='users.Professor')),
                ('vice_president_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_president_one', to='users.Professor')),
                ('vice_president_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_president_two', to='users.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.DepartmentCouncil'),
        ),
    ]
