# Generated by Django 2.1.7 on 2019-03-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcouncil',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='users.Professor'),
        ),
        migrations.AddField(
            model_name='departmentcouncil',
            name='vice_president_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_president_one', to='users.Professor'),
        ),
        migrations.AddField(
            model_name='departmentcouncil',
            name='vice_president_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_president_two', to='users.Professor'),
        ),
        migrations.AddField(
            model_name='department',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.DepartmentCouncil'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Faculty'),
        ),
    ]
