# Generated by Django 2.1.7 on 2019-03-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190316_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.DepartmentCouncil'),
        ),
    ]
