# Generated by Django 2.1.7 on 2019-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20190323_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='max_ects_per_semester',
            field=models.PositiveSmallIntegerField(default=42),
        ),
    ]
