FROM python:3.6

WORKDIR /zelda

RUN apt update && apt install -y cron

RUN mkdir code/ pids/ static/

COPY src/zelda \
     requirements.txt \
     docker/zelda/gpg/gpg.key \
     code/

RUN pip3 install -r code/requirements.txt

RUN rm code/requirements.txt

VOLUME [ \
    "/zelda/data", \
    "/zelda/logs", \
    "/zelda/static", \
    "/zelda/backups" \
]

ENV PROJECT_DIR=/zelda/code \
    PIDS_DIR=/zelda/pids \
    LOGS_DIR=/zelda/logs \
    DATA_DIR=/zelda/data \
    MEDIA_DIR=/zelda/data/media \
    STATIC_DIR=/zelda/static \
    BACKUP_DIR=/zelda/backups \
    DEBUG=no \
    MEMCACHED_HOST="cache:11211" \
    S3_HOST="zelda_s3:8000" \
    GPG_KEY_PATH=/zelda/code/gpg.key \
    GPG_RECIPIENT="zelda@zelda-edu.me"

ENTRYPOINT [ "code/scripts/start-prod.sh" ]
