FROM python:3.6

WORKDIR /zelda

RUN mkdir static/
COPY requirements.txt requirements.txt

RUN apt update
RUN apt install gettext -y

RUN pip3 install -r requirements.txt

RUN rm requirements.txt

VOLUME [ "/zelda/code" ]

ENV PROJECT_DIR=/zelda/code \
    STATIC_DIR=/zelda/static \
    DEBUG=yes \
    MEDIA_DIR="" \
    S3_HOST="zelda_s3:8000"

ENTRYPOINT [ "code/scripts/start-dev.sh" ]
