global:
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: cadvisor
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
