# Generated by Django 2.1.7 on 2019-03-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LessonSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9)),
                ('time', models.TimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('c_type', models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('lab', 'Laboratory'), ('field', 'Field')], max_length=8)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('vacancies', models.PositiveSmallIntegerField()),
                ('lesson_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.LessonSpecification')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.LessonSpecification'),
        ),
        migrations.AddField(
            model_name='class',
            name='shifts',
            field=models.ManyToManyField(to='timetable.Shift'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Lesson'),
        ),
    ]
