# Generated by Django 2.1.7 on 2019-03-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190316_1535'),
        ('timetable', '0002_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Professor'),
            preserve_default=False,
        ),
    ]
