# Generated by Django 2.1.7 on 2019-03-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190323_1426'),
        ('courses', '0003_auto_20190316_2235'),
        ('timetable', '0004_auto_20190323_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='lesson_spec',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_spec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.LessonSpecification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonspecification',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.Shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='student',
            field=models.ManyToManyField(to='users.Student'),
        ),
        migrations.AddField(
            model_name='shift',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Subject'),
            preserve_default=False,
        ),
    ]
