# Generated by Django 2.1.7 on 2019-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20190323_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='student',
            field=models.ManyToManyField(db_table='ShiftStudent', to='users.Student'),
        ),
    ]
