# Generated by Django 2.1.7 on 2019-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20190323_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='student',
            field=models.ManyToManyField(blank=True, db_table='ShiftStudent', to='users.Student'),
        ),
    ]
