# Generated by Django 2.1.7 on 2019-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_shiftexchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftexchangerequest',
            name='acceptance',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
