# Generated by Django 2.1.7 on 2019-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_shiftexchangerequest_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
