version: "3.6"
services:
  nginx:
    image: zelda-nginx:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certbot/etc/letsencrypt:/etc/letsencrypt:rw
      - ~/certbot/var/www/certbot:/var/www/certbot:rw
      - ~/nginx/conf.d:/etc/nginx/conf.d:ro
      - ~/nginx/logs/zelda:/zelda/logs:rw
      - ~/zelda/static:/zelda/static:ro
      - ~/zelda_s3/data:/zelda/s3:ro
  zelda:
    image: zelda:latest
    networks:
      zelda: {}
    deploy:
      replicas: ${DJANGO_REPLICAS}
      restart_policy:
        condition: on-failure
    depends_on:
      - cache
      - postgres
    volumes:
      - ~/zelda/data:/zelda/data:rw
      - ~/zelda/logs:/zelda/logs:rw
      - ~/zelda/static:/zelda/static:rw
      - ~/zelda/code/backups:/zelda/code/backups:rw
    env_file:
      - docker.env
  zelda_s3:
    image: zelda_s3:latest
    networks:
      zelda: {}
    deploy:
      replicas: ${DJANGO_REPLICAS}
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/zelda_s3/logs:/zelda_s3/logs:rw
      - ~/zelda_s3/data:/zelda_s3/data:rw
  cache:
    image: memcached:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  certbot:
    image: zelda-certbot:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/certbot/etc/letsencrypt:/etc/letsencrypt:rw
      - ~/certbot/var/www/certbot:/var/www/certbot:rw
  postgres:
    image: zelda-postgres:latest
    networks:
      zelda: {}
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ~/postgres/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - ~/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw
    env_file:
      - docker.env
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ~/portainer/data:/data:rw
    command: --admin-password "$2y$05$ZrXRrnLwGNwp5pmcgVsT/uME9DFmS9Z7MfYlOrymX5kmOJTkY7Hy."
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9000:9000"
    networks:
      zelda: {}
networks:
  zelda: {}
