# Generated by Django 2.1.7 on 2019-03-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('organizations', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='students',
            field=models.ManyToManyField(to='users.Student'),
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Subject'),
        ),
        migrations.AddField(
            model_name='coursespecification',
            name='course_programme',
            field=models.ManyToManyField(to='courses.CourseSubject'),
        ),
        migrations.AddField(
            model_name='coursespecification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Department'),
        ),
        migrations.AddField(
            model_name='coursespecification',
            name='entrance_exams',
            field=models.ManyToManyField(to='courses.EntranceExam'),
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSpecification'),
        ),
    ]
