# Generated by Django 2.1.7 on 2019-03-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespecification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Department'),
        ),
        migrations.AddField(
            model_name='coursespecification',
            name='entrance_exams',
            field=models.ManyToManyField(to='courses.EntranceExam'),
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSpecification'),
        ),
    ]
