# Generated by Django 2.1.7 on 2019-03-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0002_auto_20190304_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectspecification',
            name='designation',
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='designation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='students',
            field=models.ManyToManyField(to='users.Student'),
        ),
    ]
