# Generated by Django 2.1.7 on 2019-03-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190316_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Professor'),
        ),
    ]
