# Generated by Django 2.1.7 on 2019-03-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_course'),
        ('courses', '0004_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
            preserve_default=False,
        ),
    ]
