# Generated by Django 2.1.7 on 2019-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_grade_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vacancies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='coursespecification',
            name='total_semesters',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
