# Generated by Django 2.1.7 on 2019-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190323_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectspecification',
            name='field_shifts',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectspecification',
            name='lab_shifts',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectspecification',
            name='practice_shifts',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectspecification',
            name='theory_shifts',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
