# Generated by Django 2.1.7 on 2019-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190430_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='f_semester_begin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='f_semester_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_semester_begin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_semester_end_date',
            field=models.DateField(null=True),
        ),
    ]
