# Generated by Django 2.2.2 on 2019-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190512_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
